[package]
name = "shoman"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.18.0"
itertools = "0.14.0"
once_cell = "1.21.3"
rand = "0.9.1"
regex = "1.11.1"
strum = "0.27.1"
strum_macros = "0.27.1"
